#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Script generated by Vivado on Mon Dec 08 16:08:35 EST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_21 zynq_ultra_ps_e_vip_v1_0_21 xil_defaultlib xbip_utils_v3_0_14 axi_utils_v2_0_10 c_reg_fd_v12_0_10 xbip_dsp48_wrapper_v3_0_7 xbip_pipe_v3_0_10 c_addsub_v12_0_20 c_shift_ram_v12_0_19 mult_gen_v12_0_23 floating_point_v7_1_20 cmpy_v6_0_26 xfft_v9_1_14 axi_datamover_v5_1_37 axi_sg_v4_1_21 axi_dma_v7_1_36 xlconstant_v1_1_10 proc_sys_reset_v5_0_17 smartconnect_v1_0 axi_register_slice_v2_1_35)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2025.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "/tools/Xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_21 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work zynq_ultra_ps_e_vip_v1_0_21 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_2/sim/design_1_zynq_ultra_ps_e_0_2_vip_wrapper.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xbip_utils_v3_0_14 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_utils_v2_0_10 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_reg_fd_v12_0_10 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_dsp48_wrapper_v3_0_7 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_pipe_v3_0_10 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_addsub_v12_0_20 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_shift_ram_v12_0_19 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work mult_gen_v12_0_23 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work floating_point_v7_1_20 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work cmpy_v6_0_26 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xfft_v9_1_14 $vhdlan_opts -vhdl08 \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/xfft_v9_1_vh08_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xfft_v9_1_14 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_fft_convolve_0_2/src/xfft_8192/sim/xfft_8192.vhd" \
  "../../../bd/design_1/ip/design_1_fft_convolve_0_2/src/cmpy_0/sim/cmpy_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ipshared/9fa5/hdl/fft_convolve.v" \
  "../../../bd/design_1/ip/design_1_fft_convolve_0_2/sim/design_1_fft_convolve_0_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work axi_datamover_v5_1_37 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_sg_v4_1_21 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_dma_v7_1_36 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/cb19/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_axi_dma_0_5/sim/design_1_axi_dma_0_5.vhd" \
  "../../../bd/design_1/ip/design_1_dma_prn_data_0/sim/design_1_dma_prn_data_0.vhd" \
  "../../../bd/design_1/ip/design_1_dma_prn_data_1/sim/design_1_dma_prn_data_1.vhd" \
  "../../../bd/design_1/ip/design_1_dma_prn_data_2/sim/design_1_dma_prn_data_2.vhd" \
  "../../../bd/design_1/ip/design_1_dma_prn_data_3/sim/design_1_dma_prn_data_3.vhd" \
  "../../../bd/design_1/ip/design_1_axi_dma_0_6/sim/design_1_axi_dma_0_6.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/sim/bd_6d82.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_10 $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_0/sim/bd_6d82_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_17 $vhdlan_opts \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_1/sim/bd_6d82_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_2/sim/bd_6d82_arinsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_3/sim/bd_6d82_rinsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_4/sim/bd_6d82_awinsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_5/sim/bd_6d82_winsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_6/sim/bd_6d82_binsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_7/sim/bd_6d82_aroutsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_8/sim/bd_6d82_routsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_9/sim/bd_6d82_awoutsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_10/sim/bd_6d82_woutsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_11/sim/bd_6d82_boutsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_12/sim/bd_6d82_arni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_13/sim/bd_6d82_rni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_14/sim/bd_6d82_awni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_15/sim/bd_6d82_wni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_16/sim/bd_6d82_bni_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_17/sim/bd_6d82_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_18/sim/bd_6d82_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_19/sim/bd_6d82_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_20/sim/bd_6d82_s00a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_21/sim/bd_6d82_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_22/sim/bd_6d82_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_23/sim/bd_6d82_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_24/sim/bd_6d82_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_25/sim/bd_6d82_sbn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_26/sim/bd_6d82_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_27/sim/bd_6d82_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_28/sim/bd_6d82_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_29/sim/bd_6d82_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_30/sim/bd_6d82_sarn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_31/sim/bd_6d82_srn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_32/sim/bd_6d82_sawn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_33/sim/bd_6d82_swn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_34/sim/bd_6d82_sbn_1.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_35/sim/bd_6d82_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_36/sim/bd_6d82_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_37/sim/bd_6d82_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_38/sim/bd_6d82_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_39/sim/bd_6d82_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_40/sim/bd_6d82_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_41/sim/bd_6d82_m00e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_42/sim/bd_6d82_m01s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_43/sim/bd_6d82_m01arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_44/sim/bd_6d82_m01rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_45/sim/bd_6d82_m01awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_46/sim/bd_6d82_m01wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_47/sim/bd_6d82_m01bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_48/sim/bd_6d82_m01e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_49/sim/bd_6d82_m02s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_50/sim/bd_6d82_m02arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_51/sim/bd_6d82_m02rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_52/sim/bd_6d82_m02awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_53/sim/bd_6d82_m02wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_54/sim/bd_6d82_m02bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_55/sim/bd_6d82_m02e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_56/sim/bd_6d82_m03s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_57/sim/bd_6d82_m03arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_58/sim/bd_6d82_m03rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_59/sim/bd_6d82_m03awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_60/sim/bd_6d82_m03wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_61/sim/bd_6d82_m03bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_62/sim/bd_6d82_m03e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_63/sim/bd_6d82_m04s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_64/sim/bd_6d82_m04arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_65/sim/bd_6d82_m04rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_66/sim/bd_6d82_m04awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_67/sim/bd_6d82_m04wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_68/sim/bd_6d82_m04bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_69/sim/bd_6d82_m04e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_70/sim/bd_6d82_m05s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_71/sim/bd_6d82_m05arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_72/sim/bd_6d82_m05rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_73/sim/bd_6d82_m05awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_74/sim/bd_6d82_m05wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_75/sim/bd_6d82_m05bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/bd_0/ip/ip_76/sim/bd_6d82_m05e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_35 $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_7/sim/design_1_axi_smc_7.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_rst_ps8_0_99M_6/sim/design_1_rst_ps8_0_99M_6.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/sim/bd_6a39.v" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_0/sim/bd_6a39_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_1/sim/bd_6a39_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_2/sim/bd_6a39_arsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_3/sim/bd_6a39_rsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_4/sim/bd_6a39_awsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_5/sim/bd_6a39_wsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_6/sim/bd_6a39_bsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_7/sim/bd_6a39_s00mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_8/sim/bd_6a39_s00tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_9/sim/bd_6a39_s00sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_10/sim/bd_6a39_s00a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_11/sim/bd_6a39_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_12/sim/bd_6a39_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_13/sim/bd_6a39_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_14/sim/bd_6a39_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_15/sim/bd_6a39_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_16/sim/bd_6a39_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_17/sim/bd_6a39_sarn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_18/sim/bd_6a39_srn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_19/sim/bd_6a39_s02mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_20/sim/bd_6a39_s02tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_21/sim/bd_6a39_s02sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_22/sim/bd_6a39_s02a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_23/sim/bd_6a39_sarn_2.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_24/sim/bd_6a39_srn_2.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_25/sim/bd_6a39_s03mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_26/sim/bd_6a39_s03tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_27/sim/bd_6a39_s03sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_28/sim/bd_6a39_s03a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_29/sim/bd_6a39_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_30/sim/bd_6a39_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_31/sim/bd_6a39_sbn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_32/sim/bd_6a39_s04mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_33/sim/bd_6a39_s04tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_34/sim/bd_6a39_s04sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_35/sim/bd_6a39_s04a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_36/sim/bd_6a39_sarn_3.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_37/sim/bd_6a39_srn_3.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_38/sim/bd_6a39_s05mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_39/sim/bd_6a39_s05tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_40/sim/bd_6a39_s05sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_41/sim/bd_6a39_s05a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_42/sim/bd_6a39_sarn_4.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_43/sim/bd_6a39_srn_4.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_44/sim/bd_6a39_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_45/sim/bd_6a39_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_46/sim/bd_6a39_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_47/sim/bd_6a39_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_48/sim/bd_6a39_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_49/sim/bd_6a39_m00bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/bd_0/ip/ip_50/sim/bd_6a39_m00e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_7/sim/design_1_axi_smc_1_7.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fft_convolve.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/jhuang25/Documents/6.S965/6S965fp/fft_convolve/fft_convolve.cache/compile_simlib/vcs"
  fi

  echo "LIBRARY_SCAN=TRUE" >> $file

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc design_1_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
