#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Script generated by Vivado on Tue Dec 09 14:37:19 EST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +r -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_21 -libname zynq_ultra_ps_e_vip_v1_0_21 -libname xil_defaultlib -libname axi_datamover_v5_1_37 -libname axi_sg_v4_1_21 -libname axi_dma_v7_1_36 -libname axis_infrastructure_v1_1_1 -libname axis_data_fifo_v2_0_17 -libname proc_sys_reset_v5_0_17 -libname xlconstant_v1_1_10 -libname smartconnect_v1_0 -libname axi_register_slice_v2_1_35 -libname xbip_utils_v3_0_14 -libname axi_utils_v2_0_10 -libname cic_compiler_v4_0_21 -libname mult_gen_v12_0_23 -libname xbip_pipe_v3_0_10 -libname xbip_dsp48_wrapper_v3_0_7 -libname floating_point_v7_1_20 -libname cmpy_v6_0_26 -libname c_reg_fd_v12_0_10 -libname c_addsub_v12_0_20 -libname c_shift_ram_v12_0_19 -libname xfft_v9_1_14 -libname xpm_cdc_gen_v1_0_5 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_21 zynq_ultra_ps_e_vip_v1_0_21 xil_defaultlib axi_datamover_v5_1_37 axi_sg_v4_1_21 axi_dma_v7_1_36 axis_infrastructure_v1_1_1 axis_data_fifo_v2_0_17 proc_sys_reset_v5_0_17 xlconstant_v1_1_10 smartconnect_v1_0 axi_register_slice_v2_1_35 xbip_utils_v3_0_14 axi_utils_v2_0_10 cic_compiler_v4_0_21 mult_gen_v12_0_23 xbip_pipe_v3_0_10 xbip_dsp48_wrapper_v3_0_7 floating_point_v7_1_20 cmpy_v6_0_26 c_reg_fd_v12_0_10 c_addsub_v12_0_20 c_shift_ram_v12_0_19 xfft_v9_1_14 xpm_cdc_gen_v1_0_5)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2025.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/tools/Xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_21 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work zynq_ultra_ps_e_vip_v1_0_21 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_37 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_sg_v4_1_21 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_dma_v7_1_36 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/cb19/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_dma_0_0/sim/design_1_axi_dma_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_1 $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_data_fifo_v2_0_17 $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/e1e3/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_data_fifo_0_0/sim/design_1_axis_data_fifo_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_17 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_1_0/sim/design_1_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_10 $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_arinsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_rinsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_awinsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_winsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_binsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_aroutsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_routsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_awoutsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_woutsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_boutsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_arni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/sim/bd_afc3_rni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/sim/bd_afc3_awni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/sim/bd_afc3_wni_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/sim/bd_afc3_bni_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/sim/bd_afc3_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/sim/bd_afc3_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/sim/bd_afc3_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/sim/bd_afc3_s00a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/sim/bd_afc3_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/sim/bd_afc3_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/sim/bd_afc3_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/sim/bd_afc3_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/sim/bd_afc3_sbn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/sim/bd_afc3_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/sim/bd_afc3_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/sim/bd_afc3_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/sim/bd_afc3_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/sim/bd_afc3_sarn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/sim/bd_afc3_srn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/sim/bd_afc3_sawn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/sim/bd_afc3_swn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/sim/bd_afc3_sbn_1.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/sim/bd_afc3_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/sim/bd_afc3_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/sim/bd_afc3_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/sim/bd_afc3_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/sim/bd_afc3_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/sim/bd_afc3_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/sim/bd_afc3_m00e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/sim/bd_afc3_m01s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/sim/bd_afc3_m01arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/sim/bd_afc3_m01rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/sim/bd_afc3_m01awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_46/sim/bd_afc3_m01wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_47/sim/bd_afc3_m01bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_48/sim/bd_afc3_m01e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/sim/bd_afc3_m02s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/sim/bd_afc3_m02arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/sim/bd_afc3_m02rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_52/sim/bd_afc3_m02awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_53/sim/bd_afc3_m02wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_54/sim/bd_afc3_m02bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/sim/bd_afc3_m02e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/sim/bd_afc3_m03s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/sim/bd_afc3_m03arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/sim/bd_afc3_m03rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/sim/bd_afc3_m03awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/sim/bd_afc3_m03wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/sim/bd_afc3_m03bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/sim/bd_afc3_m03e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/sim/bd_afc3_m04s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/sim/bd_afc3_m04arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_65/sim/bd_afc3_m04rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_66/sim/bd_afc3_m04awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_67/sim/bd_afc3_m04wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_68/sim/bd_afc3_m04bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_69/sim/bd_afc3_m04e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_70/sim/bd_afc3_m05s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_71/sim/bd_afc3_m05arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_72/sim/bd_afc3_m05rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_73/sim/bd_afc3_m05awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_74/sim/bd_afc3_m05wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_75/sim/bd_afc3_m05bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_76/sim/bd_afc3_m05e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_35 $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/sim/bd_a878.v" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_0/sim/bd_a878_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/sim/bd_a878_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_2/sim/bd_a878_arsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_3/sim/bd_a878_rsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_4/sim/bd_a878_awsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_5/sim/bd_a878_wsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_6/sim/bd_a878_bsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_7/sim/bd_a878_s00mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_8/sim/bd_a878_s00tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_9/sim/bd_a878_s00sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_10/sim/bd_a878_s00a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_11/sim/bd_a878_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_12/sim/bd_a878_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_13/sim/bd_a878_sbn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_14/sim/bd_a878_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_15/sim/bd_a878_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_16/sim/bd_a878_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_17/sim/bd_a878_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_18/sim/bd_a878_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_19/sim/bd_a878_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_20/sim/bd_a878_s02mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_21/sim/bd_a878_s02tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_22/sim/bd_a878_s02sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_23/sim/bd_a878_s02a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_24/sim/bd_a878_sarn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_25/sim/bd_a878_srn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_26/sim/bd_a878_s03mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_27/sim/bd_a878_s03tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_28/sim/bd_a878_s03sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_29/sim/bd_a878_s03a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_30/sim/bd_a878_sarn_2.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_31/sim/bd_a878_srn_2.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_32/sim/bd_a878_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_33/sim/bd_a878_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_34/sim/bd_a878_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_35/sim/bd_a878_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_36/sim/bd_a878_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_37/sim/bd_a878_m00bn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_38/sim/bd_a878_m00e_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1_0/sim/design_1_axi_smc_1_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_block.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_por_fsm_top.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_bgt_fsm.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_device_rom.sv" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_por_fsm.sv" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_por_fsm_disabled.sv" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_tile_config.sv" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_constants_config.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_drp_arbiter.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_drp_arbiter_adc.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_register_decode.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_address_decoder.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_axi_lite_ipif.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_counter_f.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_pselect_f.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_slave_attachment.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_rf_wrapper.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_drp_control_top.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_drp_control.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_drp_access_ctrl.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_irq_req_ack.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_irq_sync.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1bufg_gt_ctrl.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_overvol_irq.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_powerup_state_irq.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_rst_cnt.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1_clk_detection.v" \
  "../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_1/synth/design_1_usp_rf_data_converter_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_14 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/b27f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_utils_v2_0_10 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/7e77/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work cic_compiler_v4_0_21 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/aef7/hdl/cic_compiler_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_cic_compiler_1_0/sim/design_1_cic_compiler_1_0.vhd" \
  "../../../bd/design_1/ip/design_1_cic_compiler_1_1/sim/design_1_cic_compiler_1_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ipshared/6fff/hdl/iq_trigger_framer.v" \
  "../../../bd/design_1/ip/design_1_iq_trigger_framer_0_1/sim/design_1_iq_trigger_framer_0_1.v" \
  "../../../bd/design_1/ipshared/bf00/src/xilinx_single_port_ram_read_first.v" \
  "../../../bd/design_1/ipshared/bf00/hdl/axi_rom.v" \
  "../../../bd/design_1/ip/design_1_axi_rom_0_0/sim/design_1_axi_rom_0_0.v" \
  "../../../bd/design_1/ipshared/4c0e/src/xilinx_true_dual_port_read_first_2_clock_ram.v" \
  "../../../bd/design_1/ipshared/4c0e/hdl/axi_ram.v" \
  "../../../bd/design_1/ip/design_1_axi_ram_0_0/sim/design_1_axi_ram_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work mult_gen_v12_0_23 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/cmpy_0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_10 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/cmpy_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_wrapper_v3_0_7 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/cmpy_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work floating_point_v7_1_20 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/cmpy_0/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work cmpy_v6_0_26 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/cmpy_0/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_fft_convolve_0_0/src/cmpy_0/sim/cmpy_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_reg_fd_v12_0_10 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/xfft_4096/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_addsub_v12_0_20 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/xfft_4096/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_shift_ram_v12_0_19 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/xfft_4096/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xfft_v9_1_14 -V200X $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/xfft_4096/hdl/xfft_v9_1_vh08_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xfft_v9_1_14 -V93 $xmvhdl_opts \
  "../../../../final.gen/sources_1/bd/design_1/ip/design_1_fft_convolve_0_0/src/xfft_4096/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_fft_convolve_0_0/src/xfft_4096/sim/xfft_4096.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ipshared/bd04/hdl/fft_convolve.v" \
  "../../../bd/design_1/ip/design_1_fft_convolve_0_0/sim/design_1_fft_convolve_0_0.v" \
  "../../../bd/design_1/ipshared/1249/hdl/mmio_interface_slave_lite_v1_0_S00_AXI.v" \
  "../../../bd/design_1/ipshared/1249/hdl/mmio_interface.v" \
  "../../../bd/design_1/ip/design_1_mmio_interface_0_0/sim/design_1_mmio_interface_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_dma_1_0/sim/design_1_axi_dma_1_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_prn_config_0/sim/design_1_axi_prn_config_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_prn_config_1/sim/design_1_axi_prn_config_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xpm_cdc_gen_v1_0_5 $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../final.gen/sources_1/bd/design_1/ipshared/5f71/hdl/xpm_cdc_gen_v1_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/7711/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../final.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xpm_cdc_gen_0_0/sim/design_1_xpm_cdc_gen_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/jhuang25/Documents/6.S965/6S965fp/final/final.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
